# Generated by Django 4.2.1 on 2023-05-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataBase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="countryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_name", models.CharField(max_length=100)),
                ("data_value", models.IntegerField()),
            ],
        ),
    ]
