# Generated by Django 4.2.1 on 2023-05-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataBase", "0002_countrydata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WebAdmin",
        ),
    ]
