# Generated by Django 4.2.1 on 2023-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataBase", "0003_delete_webadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollutionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("aqi_value", models.IntegerField()),
                ("co_aqi_value", models.IntegerField()),
                ("o_aqi_value", models.IntegerField()),
            ],
        ),
    ]
