# Generated by Django 4.2.1 on 2023-05-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataBase", "0004_pollutiondata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pollutiondata",
            name="o_aqi_value",
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="aqi_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="co_aqi_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="no2_aqi_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="no2_aqi_value",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="ozone_aqi_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="ozone_aqi_value",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="pm25_aqi_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="pollutiondata",
            name="pm25_aqi_value",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="pollutiondata",
            name="aqi_value",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="pollutiondata",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="pollutiondata",
            name="co_aqi_value",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="pollutiondata",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
